name: CI-PORTAL
on:
  push:
    branches: [ "develop" ]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
            npm i
            npm install typescript
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          # Enable linters
          eslint: true
      - name: Build The Application
        run: npm run build
