name: CI-PORTAL
on:
  pull_request:
    types: [ opened ]
    branches: [ "develop" ]






jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
            npm i
            npm install typescript
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          # Enable linters
          eslint: true
      - name: Build The Application
        run: npm run build
      - name: Generate build number
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}        
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
        
          
          
           
       
       
        
